language: node_js
node_js:
  - '10.7'
cache:
  directories:
    - node_modules
env:
  - PACKAGE=xy-chart
  - PACKAGE=sparkline
  - PACKAGE=histogram
  - PACKAGE=radial-chart
  - PACKAGE=data-table
  - PACKAGE=data-ui-theme
  - PACKAGE=forms
  - PACKAGE=network
  - PACKAGE=shared
script:
  - 'cd ./packages/$PACKAGE && npm install && npm prune && npm run test'
after_script:
  - 'cat ./packages/$PACKAGE/coverage/lcov.info | ./node_modules/.bin/coveralls'
