language: node_js

node_js:
  - 10.7

cache:
  - npm: true
  - yarn: true

matrix:
  fast_finish: true

env:
  - PACKAGE=xy-chart
  - PACKAGE=sparkline
  - PACKAGE=histogram
  - PACKAGE=radial-chart
  - PACKAGE=data-table
  - PACKAGE=data-ui-theme
  - PACKAGE=forms
  - PACKAGE=network
  - PACKAGE=shared
  - PACKAGE=demo

install:
  - npm install -g codecov

script:
  - cd ./packages/$PACKAGE
  - npm install
  - npm prune
  - npm run lint
  - npm run test

after_script:
  - codecov
